# Generated by Django 5.0.1 on 2024-11-18 22:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tanks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionUmbrales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CRITICO", "Crítico"),
                            ("BAJO", "Bajo"),
                            ("MEDIO", "Medio"),
                            ("ALTO", "Alto"),
                            ("LIMITE", "Límite"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "valor",
                    models.FloatField(
                        help_text="Valor del umbral en porcentaje (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "modificado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="umbrales_configurados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tanque",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_umbrales",
                        to="tanks.tanque",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Umbral",
                "verbose_name_plural": "Configuraciones de Umbrales",
                "db_table": "configuracion_umbrales",
                "unique_together": {("tanque", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nivel_detectado", models.FloatField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVA", "Activa"),
                            ("NOTIFICADA", "Notificada"),
                            ("ATENDIDA", "Atendida"),
                            ("RESUELTA", "Resuelta"),
                        ],
                        default="ACTIVA",
                        max_length=10,
                    ),
                ),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tanque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertas",
                        to="tanks.tanque",
                    ),
                ),
                (
                    "configuracion_umbral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alertas",
                        to="alerts.configuracionumbrales",
                    ),
                ),
            ],
            options={
                "db_table": "alertas",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialConfiguracionUmbrales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_anterior", models.FloatField()),
                ("valor_nuevo", models.FloatField()),
                ("fecha_modificacion", models.DateTimeField(auto_now_add=True)),
                (
                    "configuracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="alerts.configuracionumbrales",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_umbrales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "historial_configuracion_umbrales",
                "ordering": ["-fecha_modificacion"],
            },
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("PLATFORM", "Plataforma"),
                            ("SMS", "SMS"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENVIADA", "Enviada"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("intentos", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                (
                    "alerta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="alerts.alerta",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notificaciones",
                "ordering": ["-fecha_envio"],
            },
        ),
    ]
