# Generated by Django 5.0.1 on 2024-11-18 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0001_initial"),
        ("tanks", "0002_remove_threshold_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alerta",
            options={
                "ordering": ["-fecha_generacion"],
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
            },
        ),
        migrations.AlterModelOptions(
            name="configuracionumbrales",
            options={
                "ordering": ["tanque", "tipo"],
                "verbose_name": "Configuración de Umbral",
                "verbose_name_plural": "Configuraciones de Umbrales",
            },
        ),
        migrations.AlterModelOptions(
            name="notificacion",
            options={
                "ordering": ["-fecha_envio"],
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
            },
        ),
        migrations.AlterUniqueTogether(
            name="configuracionumbrales",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alerta",
            name="fecha_resolucion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notificacion",
            name="fecha_lectura",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="configuracionumbrales",
            name="tanque",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configuraciones_umbrales",
                to="tanks.tanque",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="configuracionumbrales",
            unique_together={("tanque", "tipo", "activo")},
        ),
        migrations.AlterModelTable(
            name="alerta",
            table="alerta",
        ),
        migrations.AlterModelTable(
            name="notificacion",
            table="notificacion",
        ),
        migrations.DeleteModel(
            name="HistorialConfiguracionUmbrales",
        ),
    ]
