# Generated by Django 5.0.1 on 2024-11-19 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0002_alter_alerta_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configuracionumbrales",
            options={
                "ordering": ["tanque", "tipo", "activo"],
                "verbose_name": "Configuración de Umbral",
                "verbose_name_plural": "Configuraciones de Umbrales",
            },
        ),
    ]
