# Generated by Django 5.0.1 on 2024-11-19 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0005_alter_alerta_configuracion_umbral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="configuracion_umbral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alertas",
                to="alerts.configuracionumbrales",
            ),
        ),
    ]
