# Generated by Django 5.0.1 on 2024-12-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0006_alter_alerta_configuracion_umbral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("ACTIVA", "Activa"),
                    ("NOTIFICADA", "Notificada"),
                    ("RESUELTA", "Resuelta"),
                ],
                default="ACTIVA",
                max_length=10,
            ),
        ),
    ]
