# Generated by Django 5.0.1 on 2024-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0007_alter_alerta_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerta",
            name="desviacion",
            field=models.FloatField(
                blank=True, help_text="Desviación del valor esperado", null=True
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="tasa_cambio",
            field=models.FloatField(
                blank=True, help_text="Tasa de cambio detectada", null=True
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="tipo_tendencia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CONSUMO_INUSUAL", "Consumo Inusual"),
                    ("PATRON_REPOSICION", "Patrón de Reposición Irregular"),
                    ("FRECUENCIA_CRITICA", "Frecuencia Crítica Alta"),
                ],
                help_text="Tipo de tendencia detectada",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="valor_anterior",
            field=models.FloatField(
                blank=True,
                help_text="Valor anterior para comparación de tendencia",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alerta",
            name="valor_esperado",
            field=models.FloatField(
                blank=True,
                help_text="Valor esperado según tendencia histórica",
                null=True,
            ),
        ),
    ]
