# Generated by Django 5.0.1 on 2024-11-13 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tanks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lectura",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Lectura",
                "verbose_name_plural": "Lecturas",
            },
        ),
        migrations.AlterField(
            model_name="lectura",
            name="fecha",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Fecha y hora de la lectura",
            ),
        ),
    ]
