version: '3.8'

services:
  web:
    build:
      context: .
      target: development
    image: gasalert-backend-dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gasalert
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=core.settings.local
    networks:
      - gasalert-net

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=gasalert
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - gasalert-net

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - gasalert-net

  celery_worker:
    build:
      context: .
      target: development
    image: gasalert-backend-dev
    command: celery -A core worker -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gasalert
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=core.settings.local
    networks:
      - gasalert-net

  celery_beat:
    build:
      context: .
      target: development
    image: gasalert-backend-dev
    command: celery -A core beat -l INFO
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gasalert
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=core.settings.local
    networks:
      - gasalert-net

networks:
  gasalert-net:
    driver: bridge

volumes:
  postgres_data: