# Generated by Django 5.0.1 on 2024-11-12 04:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActionLog",
            new_name="UserActionLog",
        ),
    ]
