# Generated by Django 5.0.1 on 2024-12-10 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_reporte",
                    models.CharField(
                        choices=[("PDF", "PDF"), ("EXCEL", "Excel"), ("CSV", "CSV")],
                        max_length=10,
                    ),
                ),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                ("rango_fechas", models.CharField(max_length=50)),
                ("archivo", models.FileField(upload_to="reportes/")),
                (
                    "estacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes",
                        to="stations.estacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_generacion"],
            },
        ),
    ]
